import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import { Toaster } from "react-hot-toast";
import { CartContextProvider } from "@/components/context/CartContext";

import Footer from "@/components/footer/page";
import { WishlistProvider } from "@/components/WishlistContext/WishlistContext"; // ← استورد WishlistProvider
import { SessionProvider } from "next-auth/react";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShopMart - Your One-Stop Online Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* ← Cart + Wishlist Context */}
           <MySessionProvider >

                   <CartContextProvider>
          <WishlistProvider>
            <Navbar />
            <div className="flex-1w-full px-4 md:px-12">
              {children}
              <Toaster />
            </div>
            <Footer />
          </WishlistProvider>
        </CartContextProvider>

           </MySessionProvider>
           

         

      </body> 
    </html>
  );
}
